### ISSUE TITLE
Suggested enhancement: GHPerson#getAllRepositories()

### ISSUE THREAD

**Issue by alexrothenberg** [kohsuke/github-api#110]
Currently `GHPerson#getRepositories()` will only get the first 30 repositories.  It would be useful (to me) to have a `getAllRepositories` that returns a map of all my repositories, if there are a lot it would follow pagination links making several github api requests.

Would you be open to this enhancement?  If so I'll work on a pull request.

Thanks

**Comment by kohsuke** [comment]
This works as expected as of 1.61
