### ISSUE TITLE
Cannot create repository in organisation

### ISSUE THREAD

**Issue by Ryuinferno** [kohsuke/github-api#118]
Got this error:

    {"message":"Validation Failed","documentation_url":"https://developer.github.com/v3/repos/#create","errors":[{"value":309572,"resource":"Repo","field":"team_id","code":"invalid"}]}

Is it due to an API update? Thank you.

**Comment by kohsuke** [comment]
This is a part of the test suite and it works for us.

The error message suggests that the team you specify is invalid?
