### ISSUE TITLE
GHRepository.getIssues(GHIssueState.CLOSED) also return pull requests

### ISSUE THREAD

**Issue by phong1990** [kohsuke/github-api#134]
Hi kohsuke,

I was using your api, it was great but there is this bug I hope you can fix it soon:
Whenever I call the function GHRepository.getIssues(GHIssueState.CLOSED), it returns a list of both issues and pull requests. 

I expect only issue though. Currently my work around is to call getPullRequests then for each issue from getIssues, I search in the whole list of pull requests to see if it is already there. Then I ignore it. But this makes my algorithm runs at O(n*m). 

Please fix it soon.

**Comment by kohsuke** [comment]
I don't think I'll change the current behavior as that is what the API returns.

If you want to filter out PRs, you can use `GHIssue.getPullRequest` to do that check in O(1). No O(n*m) computation necessary.
