### ISSUE TITLE
502 Bad Gateway error from GHRelease.uploadAsset

### ISSUE THREAD

**Issue by rowanseymour** [kohsuke/github-api#135]
I'm using https://github.com/jutzig/github-release-plugin which is built on this library. Today I started getting this error anytime I try to make a release:
```
<html><head>
[INFO] [ERROR] <title>502 Bad Gateway</title>
[INFO] [ERROR] </head><body>
[INFO] [ERROR] <h1>Bad Gateway</h1>
[INFO] [ERROR] <p>The proxy server received an invalid
[INFO] [ERROR] response from an upstream server.<br />
[INFO] [ERROR] </p>
[INFO] [ERROR] </body></html>: Server returned HTTP response code: 502 for URL: https://uploads.github.com/repos/.........
```

Might be related to http://stackoverflow.com/questions/21698009/github-api-502-error

**Comment by kohsuke** [comment]
I need a test case to reproduce this problem.

**Comment by kohsuke** [comment]
No further input from the reporter.
