### ISSUE TITLE
GHRelease issue

### ISSUE THREAD

**Issue by fred8** [kohsuke/github-api#138]
Hey @kohsuke 

I'm using the api to create a tag from a commit, then I create a release from this tag, fill up the info, body and assets. When I use the release builder, I set the prerelease and draft parameter to true. I get everything set on my github account successfully. 
That's said, when I press the button (on the github release page) to publish; all my info (title, body and files) disappear and I can just see the created tag. I'm wondering if I'm doing something wrong or if it is a bug from the library.

Here is what I m basically doing : (I extracted the code in the exact same order all the library api call)

GHRepository repository = api.getRepository(REPO_NAME);
Map<String, GHBranch> branches = repository.getBranches();
GHBranch master = branches.get(RELEASE_BRANCH_NAME);
String lastCommit = master.getSHA1();
String refName = "refs/tags/" + tagName;
GHRef ref = repository.createRef(refName, lastCommit);

final GHReleaseBuilder releaseBuilder = repository.createRelease(refName);  releaseBuilder.name(releaseName).body(body).prerelease(true).draft(true)
final GHRelease release = releaseBuilder.create()
and a bunch of release.uploadAsset(file, mimeType)

Thank you for your help!

**Comment by kohsuke** [comment]
The issue tracker isn't for user support. Please see other issues for how to report an issue.

Specifically, I need you to be more specific about the problem, what the expected result is, what actually happens, any stack trace, etc.
