### ISSUE TITLE
Github Trees support

### ISSUE THREAD

**Issue by ddtxra** [kohsuke/github-api#153]
Hello,
Thanks for this wonderful library!

I would like the library to support github trees, is it foreseen (https://developer.github.com/v3/git/trees/)?
For instance I need to retrieve this:
https://api.github.com/repos/calipho-sib/nextprot-docs/git/trees/master?recursive=1

If you would like I can try to implement this feature and I make a pull request?

**Comment by kohsuke** [comment]
Yes, a pull request would be wonderful. It should probably be a method on `GHCommit`.

**Comment by ddtxra** [comment]
Hi @kohsuke ,
I thought to implements the trees the same way as the refs. So it could be called as a method of GHRepository, the same way the GHRef works. Does it make sense?

**Comment by ddtxra** [comment]
I have sent the pull request
