### ISSUE TITLE
/repositories?

### ISSUE THREAD

**Issue by bamos** [kohsuke/github-api#157]
Hi, sorry if I'm overlooking something in the Javadoc or source,
but is the `/repositories` feature of the github API supported?

https://developer.github.com/v3/repos/#list-all-public-repositories

**Comment by suryagaddipati** [comment]
I am not sure if this is currently supported. I might be wrong though.

**Comment by acollign** [comment]
Hi Bamos,

This method [1] gives you all repositories this user owns (public and private).

Hope that helps,

[1] org.kohsuke.github.GHMyself#listRepositories()

Alex

**Comment by suryagaddipati** [comment]
@acollign I think @bamos is not looking for a particular user's repos.

**Comment by acollign** [comment]
You're absolutely right. Then it isn't supported yet but it looks quite easy to implement.

**Comment by kohsuke** [comment]
Done
