### ISSUE TITLE
Implement /search

### ISSUE THREAD

**Issue by bamos** [kohsuke/github-api#158]
https://developer.github.com/v3/search/

Hi, sorry for filing this and #157.
I'd prefer to use the repository search api.

**Comment by bamos** [comment]
My currently (ugly) workaround for this is to
use `egit-github`'s version of the search API and `kohsuke/github-api`
for everything else.
I'd prefer to only use one library, but `egit-github` doesn't support
all of the features of the `repo/readme` API.

This repo's well-written and documented, so I'd prefer to use it
for everything.
If I'm able, I'll take a look at the code and perhaps try implementing this myself.

**Comment by kohsuke** [comment]
Implemented toward 1.65.
