### ISSUE TITLE
Reading a gist in anonymonous mode causes error

### ISSUE THREAD

**Issue by madhephaestus** [kohsuke/github-api#166]
When I run 	
		
`GitHub github = GitHub.connectAnonymously();`

`GHGist gist = github.getGist(currentGist);`

I get the following exception: 

java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:464)
	at org.kohsuke.github.GitHub.getUser(GitHub.java:293)
	at org.kohsuke.github.GHGist.wrapUp(GHGist.java:106)
	at org.kohsuke.github.GitHub.getGist(GitHub.java:370)
	at ...

SInce i connected anynomously, why is it asking for the user? Is there something i can set to get it to ignore this?

**Comment by kohsuke** [comment]
Fixed.

**Comment by madhephaestus** [comment]
Can you let me know what Maven version to use to get this fix, or do i need to pull the source and build?

**Comment by KostyaSha** [comment]
You should wait until release + 1-2 days for mirroring on maven repos.

**Comment by madhephaestus** [comment]
Thank you! 

Can you post the link here when it is posted? (As a historical record thing, when I  search posts about how to fix something I hate coming to dead ends where the fix happened off camera)

**Comment by KostyaSha** [comment]
@madhephaestus i'm just monitoring commits on master to get new version ;)

**Comment by madhephaestus** [comment]
is there a link to the build instructions? or at least what the mvn params its expecting are?

**Comment by madhephaestus** [comment]
Confirmed 1.64 does not have this issue.
