### ISSUE TITLE
Pluggable persistent cache support

### ISSUE THREAD

**Issue by kohsuke** [kohsuke/github-api#168]
This is a fall out from issue #104.

It would be nice to leverage [conditional get support in GitHub](https://developer.github.com/v3/#conditional-requests) by offering some kind of optional classes that adds persistent cache on the disk.

**Comment by KostyaSha** [comment]
Two lines of code?
https://github.com/KostyaSha/github-pullrequest-plugin/blob/master/src/main/java/org/jenkinsci/plugins/github/pullrequest/GitHubPRTrigger.java#L696-L697

**Comment by kohsuke** [comment]
Great! I've updated the doc and I consder that a fix for this.
