### ISSUE TITLE
@WithBridgeMethods decorator in GHObject has no value adapterMethod

### ISSUE THREAD

**Issue by madhephaestus** [kohsuke/github-api#171]
When pulling the sources and building there is a build error in GHObject at each usage of adapterMethod. This is not a runtime problem, it will not even compile. 

Perhaps this is a problem with the decorator definition and the dependency version number problem?

build 1.6.4-SNAPSHOT 
bridge-method-annotation-1.8.jar

**Comment by madhephaestus** [comment]
Deleting the overloading decorator does not seem to break this for now.

**Comment by KostyaSha** [comment]
Logs?

**Comment by madhephaestus** [comment]
re-running the mvn with the stack trace on. I worked around it by going into the source and removing the decorator. No jar artifact was produced. I am working on a projecct in eclipse and copied the sources in to get it working. Ill replace it once the 1.64 release is posted.

**Comment by madhephaestus** [comment]
$ mvn deploy -e
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building GitHub API for Java
[INFO]    task-segment: [deploy]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/hephaestus/git/github-api/src/main/resources
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Nothing to compile - all classes are up to date
[INFO] [bridge-method-injector:process {execution: default}]
[INFO] [resources:testResources {execution: default-testResources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/hephaestus/git/github-api/src/test/resources
[INFO] [compiler:testCompile {execution: default-testCompile}]
[INFO] Nothing to compile - all classes are up to date
[INFO] [groovy:testCompile {execution: default}]
[INFO] No sources found to compile
[INFO] [surefire:test {execution: default-test}]
[INFO] Surefire report directory: /home/hephaestus/git/github-api/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.kohsuke.github.CommitTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.44 sec <<< FAILURE!
Running org.kohsuke.github.LifecycleTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
Running org.kohsuke.github.RepositoryMockTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.504 sec
Running org.kohsuke.github.RepositoryTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.013 sec <<< FAILURE!
Running org.kohsuke.github.GitHubTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.069 sec
Running org.kohsuke.github.PullRequestTest
Tests run: 8, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 1.72 sec <<< FAILURE!
Running org.kohsuke.github.GHContentIntegrationTest
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.209 sec <<< FAILURE!
Running org.kohsuke.github.AppTest

**Comment by KostyaSha** [comment]
Have you specified right credentials for passing integration tests?

**Comment by KostyaSha** [comment]
Have you read this documentation http://github-api.kohsuke.org/ ?

**Comment by madhephaestus** [comment]
Yeah this seems to be a mis-match between the @WithBridgeMethods definition and the compilers expectation of a adapterMethod being defined. Like i said, this is a compilation time problem not a runtime problem.

**Comment by kohsuke** [comment]
What JDK are you using? What is the error message?

**Comment by madhephaestus** [comment]
This is using Oracle 1.8u40. The adapterMethod is undefined in Eclipse and the project fails to build. bridge-method-annotation-1.8.jar provides @WithBridgeMethods but that decorator does not have adapterMethod defined. 

Is there some reason you can not just write the 3 overloaded methods?

**Comment by kohsuke** [comment]
You shoud get bridge-method-annotation 1.14 through dependency. How come you get 1.8?

**Comment by kohsuke** [comment]
No further input from the submitter. Closing.
