### ISSUE TITLE
Rate limiting causes silent freezing failures

### ISSUE THREAD

**Issue by madhephaestus** [kohsuke/github-api#172]
WHen Github rate limits the API will lock up until the rate limit is cleared (up to an hour!) A rate limit block should be shown as an exception and in a perfect world an event listener for remaining trys (in the API) 

I had to go in and manually print a stacktrace in RateLimitHandler.java that was being caught silently to even figure out what was happening.

**Comment by KostyaSha** [comment]
This already fixed by providing rate-limit strategies.

**Comment by KostyaSha** [comment]
Duplicates #159 and #160 #169 . Please check existed issue and code before opening issues.
