### ISSUE TITLE
Nothing is Fetched when calling repo.listNotifications();

### ISSUE THREAD

**Issue by mohamed-ennahdi** [kohsuke/github-api#181]
Hello,

I try to fetch notifications of a specific repository, but nothing is retrieved (See code below).

What am I missing ?

GHRepository repo = gh.getUser("blueimp").getRepository("jQuery-File-Upload");
System.out.println("Start");
for (GHThread t : repo.listNotifications().nonBlocking(true)) {
	System.out.println(t.getReason());
}
System.out.println("Finish");

Thank you,
Mohamed Ennahdi El Idrissi

**Comment by mohamed-ennahdi** [comment]
Well, I managed to make it work by using anonymous connection, but this returned an exception.

Is there any valid URL of a public repository where I can see notifications?

![image](https://cloud.githubusercontent.com/assets/6767325/7338165/743678f6-ec3b-11e4-8e5a-bba9c3b09e48.png)

**Comment by KostyaSha** [comment]
Please post url in text format

**Comment by mohamed-ennahdi** [comment]
https://api.github.com/repos/blueimp/jQuery-File-Upload/notifications?all=true&participating=false

**Comment by KostyaSha** [comment]
Thanks, i will try reproduce when i will have free time or maybe author will check this faster.

**Comment by mohamed-ennahdi** [comment]
I solved the problem. All I needed is to fetch notifications of a user.

So, all I had to do was to specify false for "participating" and true for "read".
