### ISSUE TITLE
Enable this to work with GitHub Enterprise

### ISSUE THREAD

**Issue by clancychilds** [kohsuke/github-api#184]
Putting this out there without much knowledge about GitHub Enterprise APIs.

Our organization uses GitHub Enterprise hosted internally. We would love to integrate Gerrit, which uses this package, with it, but the GitHub API in here is currently a static final string: https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GitHub.java#L558

Would be very nice if there was a way to use this with the apis for an internal Enterprise instance of github.

**Comment by KostyaSha** [comment]
Use GitHubBuilder and specify endpoint https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GitHubBuilder.java#L155
If you read the code you will see static GITHUB_URL used only as fallback.

**Comment by clancychilds** [comment]
Ah. Thank you. Sorry for the confusion on my part. It actually looks like the gerrit integration requirements are more complex than simply picking the right endpoints.
