### ISSUE TITLE
Need documentation for how to clone a git repo to the disk

### ISSUE THREAD

**Issue by madhephaestus** [kohsuke/github-api#196]
I can not find the API equivalent of 'git clone <url>.git' to pull the full contents of a repository to the local disk. I would also like to read from the dist a repository for local caching of files. Is this possible with github-api?

**Comment by KostyaSha** [comment]
Github is only library to API, if you learn github api pages you will see that it provides only url to git repository. For git you can use jgit.

**Comment by kohsuke** [comment]
As Kostya says, `GHRepository.gitHttpTransportUrl()` is where this library ends.

**Comment by madhephaestus** [comment]
In case someone is looking for how to do this, you can use JGIT and github-api together like this:

https://github.com/NeuronRobotics/bowler-script-kernel/blob/f1cc5473c008b9c5d6b82404b1dfc6f6b0e35c84/src/main/java/com/neuronrobotics/bowlerstudio/scripting/ScriptingEngine.java#L461
