### ISSUE TITLE
Some features of this plugin no longer work with the recent changes to api.github.com

### ISSUE THREAD

**Issue by neaket360pi** [kohsuke/github-api#202]
On June 24th, GitHub made some breaking changes to the api.  See https://developer.github.com/changes/2015-06-10-breaking-changes-to-organization-permissions-coming-on-june-24/

I am currently using the Jenkins GitHub Oauth plugin which uses the `getMyOrganizations` method defined at https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GitHub.java#L333  

Unfortunately this method relies on the API endpoint https://api.github.com/users/orgs which no longer works.

**Comment by Suirtimed** [comment]
:+1:

**Comment by ncolton** [comment]
Ah… this might explain the problems we've been having at work, which started yesterday.

**Comment by kohsuke** [comment]
According to https://developer.github.com/v3/orgs/#list-your-organizations , this API still exists. It just needs additional oauth scope.

I could be missing something, but IIUC, there's nothing this library can do, and the impact needs to be addressed by the calling app.
