### ISSUE TITLE
Followers and following pagination

### ISSUE THREAD

**Issue by cezarykluczynski** [kohsuke/github-api#213]
Is there any way to paginate over followers and following of a user?

**Comment by KostyaSha** [comment]
See code

**Comment by cezarykluczynski** [comment]
@KostyaSha Which part of the code should I look at? org.kohsuke.github.getFollowers and  org.kohsuke.github.getFollows does not seems to accept any arguments, and to always call first result page. Is there something I'm missing here?

**Comment by kohsuke** [comment]
Done in 1.72

**Comment by KostyaSha** [comment]
> See code

@cezarykluczynski  Sorry, seems posted accidentally.
