### ISSUE TITLE
GHRepository.getCompare(GHBranch, GHBranch) does not allow for cross-fork compares

### ISSUE THREAD

**Issue by if6was9** [kohsuke/github-api#218]
GHRepository.getCompare(String,String) supports cross-fork comparisons, but this does not:

https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHRepository.java#L684-L686

This is a simple fix.

**Comment by kohsuke** [comment]
Solved by merging PR.
