### ISSUE TITLE
Can not find the .github file

### ISSUE THREAD

**Issue by to2raja** [kohsuke/github-api#223]
Hi,

I am using this jar in my project. Happy to know that possible to create repo from java in GitHub. Thanks for your efforts..

I just added jars and tried to test as a java application, but I got an error, which says .github folder is not available.

Here is my code,

	public static void main(String[] args) throws IOException {
		// TODO Auto-generated method stub
		String name = "name - new-repo";
		String description = "description - this is my new repository";
		String homepage = "homepage - http://www.kohsuke.org/";
		boolean isPublic = true;
		
		GitHub github = GitHub.connectUsingPassword("myUserName", "password");
		GHRepository repo = github.createRepository(name, description, homepage, isPublic);
		
		System.out.println(repo.getOwner());
		System.out.println(repo.getLanguage());
		
	}

And the exception is as follows,

Exception in thread "main" java.io.FileNotFoundException: C:\Users\user\ .github (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at org.kohsuke.github.GitHub.connect(GitHub.java:144)
	at com.votsh.repository.GitRepo.main(GitRepo.java:28)

Thanks in advance

**Comment by to2raja** [comment]
Any update in this?

**Comment by gansai** [comment]
Hi @to2raja,
You need to create a file named = '.github'  in "C:\Users\user\" folder. That .github file will contain two lines:
login=loginName
password=loginPassword.

Hope it helps. Let us know if it works.

**Comment by oleg-nenashev** [comment]
BTW, the provided stacktrace does not fit the code you've provided. You don't call GitHub.connect() in it. IIRC <code> GitHub.connectUsingPassword()</code> should not require the <code>.github</code> as I see from the code.
