### ISSUE TITLE
Push to repo

### ISSUE THREAD

**Issue by to2raja** [kohsuke/github-api#229]
I am able to create repository in GitHub. it s going good.

Now I want to push my local folder to this created repo. Is it possible to do using this library? I m using JGit to push now, which took too much time to push to the repo. I am able to push in 3 minutes via terminal, but JGit tooks 25 minutes to push the same folder.

Thanks in advance

**Comment by KostyaSha** [comment]
Duplicates https://github.com/kohsuke/github-api/issues/196#issuecomment-109643747
