### ISSUE TITLE
Access to raw JSON for issues?

### ISSUE THREAD

**Issue by io7m** [kohsuke/github-api#235]
Hello.

I currently use the `github-api` package to maintain a local mirror of my repositories. I would like to be able to maintain a local copy of all issues, open or closed. Right now, I could use the API to pull a list of GHIssue objects and then manually serialize them all. However, this suffers from two problems: It's a maintenance burden, and I'd need to constantly check the API to ensure that new fields haven't been added that my manual serialization would otherwise miss. The `github-api` package obviously has access to the raw JSON, so is there any way that it could expose it so that I could write it directly to disk?

**Comment by kohsuke** [comment]
We don't keep JSON in memory, so you'd be better off making direct HTTP calls by using `GHIssue.getApiURL()`.

**Comment by io7m** [comment]
OK, thanks.
