### ISSUE TITLE
Question - Stargazers and stars release.

### ISSUE THREAD

**Issue by pedrovgs** [kohsuke/github-api#239]
Hi @kohsuke! First of all, thanks for this library it's really easy to use and really useful :)

I'd like to know when you are going to publish [the last functionality you've added to the project](https://github.com/kohsuke/github-api/commit/2603b5a402a3f0669f5828c316c4d589cf1d1e1b). I'm working on a project where I need this awesome feature :).

Thanks!

**Comment by kohsuke** [comment]
I just released 1.72.

In the future, for Q&A, please use the mailing list. The bug tracker is for bugs.
