### ISSUE TITLE
How to get statistics using this library

### ISSUE THREAD

**Issue by arjunvijayvargiya** [kohsuke/github-api#241]
Hi @kohsuke ,
                         I am using this library for long in implementing many of my projects. I am facing an issue as I am not able to get statistics of a particular user in a repo? How to do that?

**Comment by kohsuke** [comment]
Can you point me to the relevant part of the GitHub API doc? I don't see anything statistics-ish in https://developer.github.com/v3/users/

**Comment by kohsuke** [comment]
No further input from the reporter
