### ISSUE TITLE
Not able to specify client Id and client secret to connect using OAuth

### ISSUE THREAD

**Issue by sbhaktha** [kohsuke/github-api#256]
Hi,

I would like the 5000 requests rate limit / hour offered by GitHub for authenticated requests-- to do this if you're using OAuth you need to send the client Id and secret. Please see : https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications . But I don't see a way to do that via your API. Looks like they take only the OAuth Access token. Is there a way to pass these? Or I am stuck with the 60 requests / hour limit.

Appreciate your help!
Thanks,
Sumithra

**Comment by sbhaktha** [comment]
Also, is there a way to make these Conditional Requests so that I can stay within limit? https://developer.github.com/v3/#conditional-requests Thanks!

**Comment by kohsuke** [comment]
See `GitHubBuilder`
