### ISSUE TITLE
Add Support for the Protected Branches API

### ISSUE THREAD

**Issue by kmadel** [kohsuke/github-api#262]
See https://developer.github.com/changes/2015-11-11-protected-branches-api/
and
https://developer.github.com/v3/repos/#enabling-and-disabling-branch-protection

Admittedly, this is a beta feature, but would certainly be nice to modify the protected status and protection context automatically from, say, a Jenkins job.

This is also available for GHE as of v2.5

**Comment by kohsuke** [comment]
Fixed in 27e855ddbde2feb9e4d07b21c0f613882cb46dfb
