### ISSUE TITLE
github.getRepository does not work for Enterprise github instance

### ISSUE THREAD

**Issue by ramachandranbakthavachalam** [kohsuke/github-api#263]
github.getRepository method appends /repos/ to the url which does not work for Enterprise github instance.

**Comment by kohsuke** [comment]
I don't have ready access to GHE. Can you give me what URL it's accessing and what it should be instead?

I'm quite a bit surprised that something this basic has escaped everyone's attention thus far. Are you sure this is a problem in the library, as opposed to your deployment?

**Comment by jdeanquin-dg** [comment]
Hello @ramachandranbakthavachalam the following code gets a pullRequest from my enterprise repository
`			`GitHub github = GitHub.connect("myUsername", "MyToken");
			GHRepository repo = github.getRepository("myOrganisation/theRepo");
			GHPullRequest pullRequest = repo.getPullRequest(41);
`

**Comment by Shredder121** [comment]
Maybe you have a token that doesn't include the necessary visibility?
GitHub tends to return 404s if you are not allowed to see something.

**Comment by kohsuke** [comment]
Looks like the problem was in the reporter's access control or usage.
