### ISSUE TITLE
More meaning toString implementations

### ISSUE THREAD

**Issue by szpak** [kohsuke/github-api#268]
Currently many of the GH* objects don't have meaninful `toString()` implementation. As details seem to be already initialized in most cases it would be useful to see something like:

```
GHMIlestone: title=0.1.3, state=CLOSED, number=34
```

instead of
```
org.kohsuke.github.GHMilestone@72d6b3ba
```

**Comment by kohsuke** [comment]
Fixed in cde501af8de9b871dc53e656aac6b4bd22196dcb
