### ISSUE TITLE
Pull request mergeability is boolean but should be trinary

### ISSUE THREAD

**Issue by PerilousApricot** [kohsuke/github-api#275]
According to the API docs: 

"The value of the mergeable attribute can be true, false, or null. If the value is null, this means that the mergeability hasn't been computed yet, and a background job was started to compute it. Give the job a few moments to complete, and then submit the request again. When the job is complete, the response will include a non-null value for the mergeable attribute."

This casting currently treats "null" as "can not merge", which cascades down to other plugins. Should the returned type be expanded?

**Comment by KostyaSha** [comment]
And while you will calculate single variable you can: 
- always get to null values because of recalculates
- consume rate limits
- may be not interesting in this status, but client would continue sending requests
All code that i know care about status themselve.

**Comment by KostyaSha** [comment]
And btw, that what i wrote to GH API developers about, but didn't get any answer.

**Comment by PerilousApricot** [comment]
I'm not sure I follow? I ended up chasing this down because Jenkins thought every commit it saw was unmergeable and refused to build them, when in actuality it just didn't know whether or not it could be merged. Seems like letting the API say "null" instead of coercing the 3 possible inputs to 2 outputs lets people downstream do the right thing

**Comment by KostyaSha** [comment]
This the library it returns what gh API provides. API provides 3 states, everything right.

**Comment by kohsuke** [comment]
This library correctly defines `Boolean GHPullRequest.getMergeable()` to represent the tri-state.

@PerilousApricot it seems to me that you should be actually filing this bug to whatever Jenkins plugin that takes this `Boolean` return value and coerce that to `boolean`.

**Comment by PerilousApricot** [comment]
@kohshuke I have the utmost respect for you. I was using Jenkins before it
was called Jenkins

With the 2.0 push, isn't the point to make the common case easier? GitHub
and Jenkins blow up for an easily triggerable reason. It's a "plugin" but
probably the most common integration people want to make.

On Friday, June 3, 2016, Kohsuke Kawaguchi <notifications@github.com> wrote:

> This library correctly defines Boolean GHPullRequest.getMergeable() to
> represent the tri-state.
>
> @PerilousApricot <https://github.com/PerilousApricot> it seems to me that
> you should be actually filing this bug to whatever Jenkins plugin that
> takes this Boolean return value and coerce that to boolean.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kohsuke/github-api/issues/275#issuecomment-223734370>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAFsqjDdKsQmwJTwQ4NP9jUxBIOShOHnks5qIPZ9gaJpZM4IQFI8>
> .
>


-- 
It's dark in this basement.
