### ISSUE TITLE
OkHttp is out of date

### ISSUE THREAD

**Issue by mh-park** [kohsuke/github-api#290]
OkUrlFactory is deprecated, so using the Cache is not the same as described on homepage.

**Comment by Shredder121** [comment]
When was it deprecated?
We're still on OkHttp 2.x, and it's not deprecated for me.

**Comment by mh-park** [comment]
It was deprecated later on in 2.x, and removed in 3.x.

Some extra clarification: If we are to use this github library with the most recent version (3.4.1) of OkHttp (let's say, to use a cache like it says on `http://github-api.kohsuke.org/`), we wouldn't be able to because OkUrlFactory doesn't exist anymore.

**Comment by Shredder121** [comment]
> If we are to use this github library with the most recent version (3.4.1) of OkHttp 

That isn't possible, since they changed package names as well.
So all classes (as we use them in `github-api` don't "exist" anymore.

But which version was it deprecated then?
I'm on 2.7.5, and see no such deprecation.

**Comment by kohsuke** [comment]
Looks like OkUrlFactory is being deprecated in OkHttp 3.x. From their javadoc:

```
/**
 * @deprecated OkHttp will be dropping its ability to be used with {@link HttpURLConnection} in an
 * upcoming release. Applications that need this should either downgrade to the system's built-in
 * {@link HttpURLConnection} or upgrade to OkHttp's Request/Response API.
 */
```

I don't think there's anything this library can do here.
