### ISSUE TITLE
Missing support for determining if authenticated user is organization owner

### ISSUE THREAD

**Issue by WesleyTrescott** [kohsuke/github-api#293]
Some operations involving teams within organizations require the authenticated user to be an organization owner.  As far as I can tell, there is no way to get this information in the current implementation.  The following stackoverflow answer illustrates the the information I am trying to retrieve: [http://stackoverflow.com/a/28190753](http://stackoverflow.com/a/28190753)

**Comment by Shredder121** [comment]
Can you turn around the link?
You have the link in the text, and the text(nothing) in the link.

**Comment by WesleyTrescott** [comment]
Thanks for notifying me, it should work now.

**Comment by kohsuke** [comment]
Implemented toward 1.81
