### ISSUE TITLE
How to find a pull request using the Search API and get its details?

### ISSUE THREAD

**Issue by adamsiemion** [kohsuke/github-api#298]
Is there a quicker/better way to get a `GHPullRequest` instance from `searchIssues()` results?

I have got`String sha1` and `GHRepository repository` instances and the following code:

```
final PagedSearchIterable<GHIssue> list = githubClient.searchIssues().q(sha1).list();
final GHIssue issue = list.iterator().next();
final String pullRequestUrl = issue.getPullRequest().getUrl().toString();
final int pullRequestNumber = Integer.valueOf(pullRequestUrl.substring(pullRequestUrl.lastIndexOf('/')+1));
final GHPullRequest pullRequest = repository.getPullRequest(pullRequestNumber);
```

**Comment by kohsuke** [comment]
We have a mailing list for Q&A https://groups.google.com/forum/#!forum/github-api, so let's not use issue tracker for questions. Thanks!
