### ISSUE TITLE
Pull Request Reviews API

### ISSUE THREAD

**Issue by masud-technope** [kohsuke/github-api#305]
Each PR review has three outcomes according to the documentation.
https://help.github.com/articles/about-pull-request-reviews/
- Comment:

- Approve:

- Request changes

Right now, I can only see the review comments using this code with your API
`request.listReviewComments().iterator();`
Can I see the "Approve" and "Request changes" as well? Do you have a plan to add them?
@kohsuke

**Comment by kohsuke** [comment]
Hmm, I'm not seeing this in their API documentation, for example [here](https://developer.github.com/v3/pulls/comments/). Does anyone know where this API is documented?

**Comment by swagatata** [comment]
here is the API doc for PR reviews https://developer.github.com/v3/pulls/reviews/

**Comment by henryju** [comment]
The API was initially in "beta" state, but now it seems to be final.
