### ISSUE TITLE
Delete OAuth Token

### ISSUE THREAD

**Issue by srepollock** [kohsuke/github-api#308]
I'm creating a Gist manager Android application [GoodGists](https://github.com/srepollock/GoodGists) and I'm trying to get something working where I log out and delete the file where the OAuth key was saved. When I delete this and try to sign in again it's not allowing me to. Where do I delete the token created in the API?

**Comment by KostyaSha** [comment]
I think you need read GitHub API documentation and don't ask it in library that only provides the way to do auth calls.

**Comment by kohsuke** [comment]
We have a mailing list for Q&A https://groups.google.com/forum/#!forum/github-api, so let's not use issue tracker for questions. Thanks!

**Comment by srepollock** [comment]
Thanks. Sorry just saw the email
