### ISSUE TITLE
Update OkHttp usage

### ISSUE THREAD

**Issue by ScottPierce** [kohsuke/github-api#312]
`OkUrlFactory` is deprecated and will be removed in a newer version. It also seems you are using an old version of OkHttp in your `OkHttpConnector`, so it's not compatible.

**Comment by kohsuke** [comment]
As you said, `OkUrlFactory` is deprecated in OkHttp3, so there's no easy way to implement `HttpConnector` for newer versions of OkHttp. I don't see anything this library could do here, and `OkHttpConnector` is a convenience extra and not a critical part of this library anyway.

**Comment by rmetzger** [comment]
Another problem of the `okhttp3.OkUrlFactory` is that it does not support OkHttp interceptors, making logging of HTTP calls with OkHttp impossible.
