### ISSUE TITLE
Adding users to organization-owned repos not possible

### ISSUE THREAD

**Issue by ToWi87** [kohsuke/github-api#317]
Adding users to organization-owned repositories fails for me due to GHRepository#verifyMine() saying "Operation not applicable to a repository owned by someone else" which is quite correct, still not OK if the logged in user has respective privileges on the repository.

Proposal: remove this check and wait for GitHub to return HTTP 401/403.

**Comment by kohsuke** [comment]
Indeed. Fixed in 1.82.
