### ISSUE TITLE
getLabels() call for a pull request results in downstream 404s

### ISSUE THREAD

**Issue by benpatterson** [kohsuke/github-api#319]
When calling `.getLabels()` with a pull request object, the pull request object's url is overridden to include `/issues/` in the path, rather than `/pulls/`. This can cause subsequent 404s when attempting to access pull request-specific API endpoints, like `getCommits()`, which require a pull request url.

See https://github.com/jenkinsci/ghprb-plugin/issues/441 for some backstory.

**Comment by kohsuke** [comment]
Fixed in 1.82.

**Comment by benpatterson** [comment]
Thanks for the fix! We'll look to incorporate it downstream. :tada:
