### ISSUE TITLE
API response time

### ISSUE THREAD

**Issue by sergiofigueras** [kohsuke/github-api#322]
Hello guys,

I'm in a trouble here and I would like to know if some of you guys have passed through the same or if its something new.

Basically after using some calls on GHRepository, with this operation:

```
final PagedSearchIterable<GHIssue> list = githubClient.searchIssues()
        .q("type:pr")
        .q(String.format("repo:%s", githubRepoName(repoName)))
        .q(commitId)
        .list();
```

it seems that by some reason my request is queued, and it might take >10min to take the results, which is bringing me several timeout operations.

Does it happened with you before? Is that something that I must configure on github-api?

**Comment by kohsuke** [comment]
Let's use https://groups.google.com/forum/#!forum/github-api for Q&A, and keep issue tracker for bugs.
