### ISSUE TITLE
Support new merge methods (squash/rebase) for Github Pull Requests

### ISSUE THREAD

**Issue by NicholasBoll** [kohsuke/github-api#326]
**Note:** This is part of a developer preview, so it might be too early to implement.

According the version 3 of the github API, new merge methods (`squash` and `rebase`) have been added, `merge` being the default: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

In [GHPullRequest#L294](https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHPullRequest.java#L294), `merge_method` could be added to support different merge methods. Either the `merge` method could be overloaded to support different merge methods or methods for squashing and rebasing could be added.

**Comment by greggian** [comment]
Note, merge_method is now out of preview. PR updated accordingly.
