### ISSUE TITLE
How can I get Latest Release of Repository?

### ISSUE THREAD

**Issue by kamontat** [kohsuke/github-api#341]

**Comment by oleg-nenashev** [comment]
See http://mvnrepository.com/artifact/org.kohsuke/github-api

**Comment by kamontat** [comment]
No, I mean in program GHRepository have method call listReleases but it return all tag that repository have so how can i get only the latest one?

**Comment by emlagowski** [comment]
As I see in code you can't do that in one call at this moment. Obviously you can get a full list and take first element. However, [here](https://developer.github.com/v3/repos/releases/#get-the-latest-release) is a method that allows you to get the latest release. It shouldn't be difficult to add that feature. I can try to add this in a few days, but no promises.
