### ISSUE TITLE
Building failing due problematic repository server

### ISSUE THREAD

**Issue by sergiofigueras** [kohsuke/github-api#344]
Hello guys,

Our build is failing due an bad repository. It started two days ago.

```org.kohsuke:github-api:jar:1.77 -> com.infradna.tool:bridge-method-annotation:jar:1.14 -> org.jenkins-ci:annotation-indexer:jar:1.4: Failed to read artifact descriptor for org.jenkins-ci:annotation-indexer:jar:1.4: Could not transfer artifact org.jenkins-ci:jenkins:pom:1.26 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): Failed to transfer file: http://repo.jenkins-ci.org/public/org/jenkins-ci/jenkins/1.26/jenkins-1.26.pom. Return code is: 502 , ReasonPhrase:Bad Gateway. -> [Help 1]```

I also checked https://repo.jenkins-ci.org/public/org/jenkins-ci/jenkins/1.26/jenkins-1.26.pom, but its giving 504 TIMEOUT.
Is anybody facing this too?

**Comment by kohsuke** [comment]
This must have been a transient failure.
