### ISSUE TITLE
Refactor to allow for additional HTTP headers

### ISSUE THREAD

**Issue by cosmocracy** [kohsuke/github-api#353]
For new/experimental functionality, the GitHub API requires the submission of an additional header to enable features (see, for example, the [API documentation note](https://developer.github.com/v3/repos/) below related to the new Topics attributes):

![image](https://cloud.githubusercontent.com/assets/10222432/24561770/15a10854-1616-11e7-97a3-cf9b61987b87.png)

Currently while the HTTP mechanisms are well-factored, they are only plugable via changes to the source code of this library.  To ease extensibility (and meet the needs of additional headers), please consider either: 
 - Implementing a Factory-style improvement that would allow for us to provide a ```Requester``` that could, for examlpe include the headers within the implementation of ```buildRequest```, or
 - Provide a pathway for injecting headers into the ```Requester```'s ```headers``` property, possibly via a static-level "DefaultHeaders" that is publicly available.

**Comment by kohsuke** [comment]
I don't understand the motivation for this. This library has no "extensibility" in the sense of defining additional API (like "topics" in your example) outside. The only way to do so is to change the source code of this library.
