### ISSUE TITLE
Unable to find documentation for issue search

### ISSUE THREAD

**Issue by Rahamathulla** [kohsuke/github-api#364]
I would like to see the documentation for sample issue search.

Can you please help with it.

**Comment by oleg-nenashev** [comment]
* http://github-api.kohsuke.org/apidocs/index.html?org/kohsuke/github/GitHub.html
* http://github-api.kohsuke.org/apidocs/index.html?org/kohsuke/github/GHIssueSearchBuilder.html

**Comment by Rahamathulla** [comment]
I checked those. can you please help with some sample code.

how to invoke search. currently I am seeing the GHIssueSearchBuilder is just to build the criteria[also its missing language etc.,].

**Comment by oleg-nenashev** [comment]
Sorry, I doubt there is a developer documentation in this repo. But you can find several exampes in GitHub. E.G. https://github.com/triller-telekom/github-statistics/blob/3139e3ca505c2e437e360aedbc73c9e211db6f4e/src/org/eclipse/smarthome/githubstats/IssueHandler.java#L26 . Syntax for such raw queries is documented here: https://help.github.com/articles/search-syntax/

Search query: https://github.com/search?q=GHIssueSearchBuilder&type=Code&utf8=%E2%9C%93

**Comment by Rahamathulla** [comment]
Thanks for your help oleg-nenashev. Much appreciated
