### ISSUE TITLE
<null> fields yeld NPE on getX operations.

### ISSUE THREAD

**Issue by baranowb** [kohsuke/github-api#372]
GHPullRequest@645aa696[base=org.kohsuke.github.GHCommitPointer@7ce026d3,head=org.kohsuke.github.GHCommitPointer@7ce69770,additions=1,merged=false,mergeable=<null>,deletions=1,assignee=<null>,state=open,number=1903,comments=2,labels=<null>,title=XXXXX,milestone=<null>,url=PR_URL,id=122473208]

Will throw NPE on .getMergeable()

**Comment by baranowb** [comment]
https://developer.github.com/v3/pulls "The value of the mergeable attribute can be true, false, or null. If the value is null, this means that the mergeability hasn't been computed yet, and a background job was started to compute it. Give the job a few moments to complete, and then submit the request again. When the job is complete, the response will include a non-null value for the mergeable attribute."

This should be reflected in field. Worse case scenario with Boolean, so null can be one of potential values or with proper enum YES,NO, NOT_DEFINED( or something similar)

**Comment by kohsuke** [comment]
Without stack trace, I'm afraid I cannot fix this.

**Comment by baranowb** [comment]
I can include stack trace but it will just indicate place in our code which triggers NPE due to unboxing of Boolean: https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHPullRequest.java#L55
Getter/field type is wrong. Either getter must indicate full use of three potential value( as opposed to boolean) - null, True, False/(or True, False(false, null) or it should be changed to enum.
