### ISSUE TITLE
add a comment to a pull Request

### ISSUE THREAD

**Issue by sbuisson** [kohsuke/github-api#380]
Hello,
It's seem that your api don't implement the creation of a comment for a pullRequest:
POST /repos/:owner/:repo/pulls/:number/comments

the doc here:
https://developer.github.com/v3/pulls/comments/#create-a-comment

**Comment by iraleigh** [comment]
This was confusing to me at first, but it is important to note that` GHPullRequest` inherits from `GHIssue`. This gives it a method `.comment()`

e.g.

```
GHPullRequest pullRequest = ...
pullRequest.comment("Blue skies, smiling at me....");
```

**Comment by kohsuke** [comment]
This is implemented as `GHPullRequestReviewComment` which is separate from `GHIssueComment`
