### ISSUE TITLE
64-bit id support

### ISSUE THREAD

**Issue by Raimmaster** [kohsuke/github-api#393]
When working with the GitHub statuses API, it appears that IDs that surpass the 32-bit mark it throws the following exception: 
`com.fasterxml.jackson.core.JsonParseException: Numeric value (x) out of range of int`. 
I haven't checked if it goes all the way to the [jackson-core](https://github.com/FasterXML/jackson-core) project, but the status IDs now generated have gone past 4294967295, which is the maximum uint value.

It'd be great if we could fix this, and I'd be happy to do the pull request if given some pointers and pairing. Thanks beforehand.

**Comment by johnou** [comment]
Integer.MAX_VALUE in Java is 2147483647, to fix this all "id" fields for data transfer objects used by jackson will need to be changed to long.

**Comment by johnou** [comment]
https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHObject.java#L28 already has long for id, @Raimmaster can you provide a full error message / stacktrace please?

**Comment by Raimmaster** [comment]
Yes, that's why I said that it even surpassed the maximum uint value. Regardless, the change must be done in both repos, right? Or am I mistaken in that sense?

**Comment by johnou** [comment]
both repos? no.. https://github.com/kohsuke/github-api/commit/7735edeae87652c1fa8196e7956851a39f5a84d4#diff-94a87075551ce5757abefb5b3537ba80 this change was done 10 days ago are you running github-api-1.90?

**Comment by Raimmaster** [comment]
Give me a moment. We're working with sonarqube, so apparently it is also using the github-api version you mentioned: https://github.com/SonarSource/sonar-github/blob/master/pom.xml#L93

**Comment by Raimmaster** [comment]
Sadly, the release has not been updated, and it's using the 1.76 version. https://github.com/SonarSource/sonar-github/releases/tag/1.4-rc1

**Comment by Raimmaster** [comment]
Thanks, @johnou. I'll focus in updating the sonarcube's dependency version. Hopefully that'll solve it. Closing this for now.
