### ISSUE TITLE
GHPullRequest.getMergeable() never returns True

### ISSUE THREAD

**Issue by jamesdh** [kohsuke/github-api#399]
This used to work, but a change in the last couple months seems to have broken this for us. 

We have some Jenkins Pipeline code that does some automatic PR creation + merging for specific use cases. Initially when creating the PR, GitHub isn't always immediately able to act on it, so we would check if it were mergeable before actually attempting to merge:

```
GHPullRequest pull = repo.createPullRequest("Release $version", "master", "production", body)
while(!pull.getMergeable()) {
    echo "PR not yet mergeable, retrying..."
}
pull.merge("Merged & released via [${env.BUILD_NUMBER}](${env.BUILD_URL})", pull.getHead().getSha())
```

Now however, pull.getMergeable() never returns true if it returns false the first time it is called (which is basically every time), so it just sits in that loop, retrying. 

Again, this only broke after we recently updated all of our plugins on our Jenkins instance, so it seems a recent change is causing this but I've been unable to identify what it might be in the recent history.

**Comment by jamesdh** [comment]
Also worth noting that this *does* create the pull request on GitHub. We can just never act on it after creating it because of this issue.

**Comment by kohsuke** [comment]
Fixed toward 1.91.

**Comment by jamesdh** [comment]
Awesome, thank you! Any chance we can get 1.91 or 1.92 released to the Jenkins plugin portal? :)

**Comment by jamesdh** [comment]
@kohsuke anything I can do to help get this released into the wild?
