### ISSUE TITLE
Do not throw new Error()

### ISSUE THREAD

**Issue by samrocketman** [kohsuke/github-api#400]
https://github.com/kohsuke/github-api/search?utf8=%E2%9C%93&q=%22new+Error%22&type=

In general, this seems to be a bad idea.  See also comments in https://github.com/jenkinsci/ghprb-plugin/pull/570. This PR for the GHPRB plugin is left with the dilemma of catching throwable because there's no other choice since this API throws `java.lang.Error`.

A quote from `java.lang.Error` javadoc:

> An `Error` is a subclass of `Throwable` that indicates serious problems that a reasonable application should not try to catch.

Instead, consider throwing `IllegalStateException`.

**Comment by jglick** [comment]
Care to file a PR for it?

**Comment by oleg-nenashev** [comment]
Well, even `IllegalStateException` is not ideal, checked exceptions would be better. But it requires introducing new APIs

**Comment by samrocketman** [comment]
Yeah, I don't mind filing.  I was going to bed last night so filed it before forgetting.

**Comment by samrocketman** [comment]
Looks like PR has been filed.

**Comment by kohsuke** [comment]
Merged #401
