### ISSUE TITLE
How to authenticate using oauth in code?

### ISSUE THREAD

**Issue by lukas2005** [kohsuke/github-api#405]
Hello I have 2fa auth enabled on my acc and because of that I need to auth using oauth (and I'd also like for the creds to be hard coded but I wont do that with my pass). This is what I have tried to do that:
```java
           GitHub github = new GitHubBuilder().withOAuthToken("TOKEN", "EMAIL").build();
```
but it just thrown an error.
Please help

EDIT:
another question:
is it possible to auth using client secret and id? (https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications)

**Comment by kohsuke** [comment]
Issue tracker is not a place to do Q&A.
