### ISSUE TITLE
GHRepository.listCommits() returns java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by Zhang-Nick** [kohsuke/github-api#433]
timed out accessing https://api.github.com/repositories/455600/commits?page=196; will try 2 more time(s)

When I used the GHRepository.listCommits() to get all the commits from repo " facebook/hhvm",it returns me timed out

**Comment by kohsuke** [comment]
I don't see how this is a problem of the library, it sounds like GitHub failing with timeout.
